name: twit2-dev
services:
    # User Service
    svc-users:
        build: projects/svc-users
        restart: on-failure
        ports:
            - 3201:3201
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - DB_NAME=t2-users
            - DB_URL=mongodb://host.docker.internal:27017
            - MQ_URL=amqp://host.docker.internal:5672
            - HTTP_PORT=3201

        depends_on:
            rabbitmq:
                condition: service_healthy

    # Authentication Service
    svc-auth:
        build: projects/svc-auth
        restart: on-failure
        ports:
            - 3200:3200
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - DB_NAME=t2-auth
            - DB_URL=mongodb://host.docker.internal:27017
            - MQ_URL=amqp://host.docker.internal:5672
            - HASH_ALGO=bcrypt
            - HASH_ROUNDS=14
            - HTTP_PORT=3200

        depends_on:
            rabbitmq:
                condition: service_healthy

    # Posts Service
    svc-posts:
        build: projects/svc-posts
        restart: on-failure
        ports:
            - 3202:3202
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - DB_NAME=t2-posts
            - DB_URL=mongodb://host.docker.internal:27017
            - MQ_URL=amqp://host.docker.internal:5672
            - HTTP_PORT=3202

        depends_on:
            rabbitmq:
                condition: service_healthy

    # Posts Service
    svc-cdn:
        build: projects/svc-cdn
        restart: on-failure
        ports:
            - 3400:3400
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - MQ_URL=amqp://host.docker.internal:5672
            - HTTP_PORT=3400
        volumes:
            - ./data/cdn/content:/app/content/
        depends_on:
            rabbitmq:
                condition: service_healthy

    # Frontend app
    app-frontend:
        build: projects/frontend
        restart: on-failure
        ports:
            - 3000:3000
        extra_hosts:
            - "host.docker.internal:host-gateway"

        depends_on:
            rabbitmq:
                condition: service_healthy