name: twit2-dev
services:
    # User Service
    svc-users:
        build: projects/svc-users

    # Authentication Service
    svc-auth:
        build: projects/svc-auth

    # Posts Service
    svc-posts:
        build: projects/svc-posts

    # Posts Service
    svc-cdn:
        build: projects/svc-cdn

    # Frontend app
    app-frontend:
        build: projects/frontend

    # Admin frontend app
    app-admin-frontend:
        build: projects/admin-frontend
