name: twit2-dev
services:
    # user service
    svc-users:
        build: projects/svc-users
        ports:
            - 3201:3201
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - DB_NAME=t2-users
            - DB_URL=mongodb://host.docker.internal:27017
            - MQ_URL=amqp://host.docker.internal:5672

        depends_on:
            rabbitmq:
                condition: service_healthy